# Generated by Django 5.2.6 on 2025-10-04 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift1_start', models.TimeField()),
                ('shift1_end', models.TimeField()),
                ('shift2_start', models.TimeField()),
                ('shift2_end', models.TimeField()),
                ('shift3_start', models.TimeField()),
                ('shift3_end', models.TimeField()),
                ('display_format', models.CharField(default='alphabetic', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('plan_shift1', models.IntegerField(default=0)),
                ('plan_shift2', models.IntegerField(default=0)),
                ('plan_shift3', models.IntegerField(default=0)),
                ('actual_count', models.IntegerField(default=0)),
                ('total_downtime_min', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=1)),
                ('plan', models.IntegerField(default=0)),
                ('actual', models.IntegerField(default=0)),
                ('downtime_min', models.FloatField(default=0)),
                ('efficiency', models.FloatField(default=0.0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andon.station')),
            ],
        ),
        migrations.CreateModel(
            name='SectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('fault_time', models.DateTimeField(blank=True, null=True)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('calltype', models.CharField(blank=True, max_length=20)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andon.station')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plan', models.IntegerField(default=0)),
                ('actual_count', models.IntegerField(default=0)),
                ('efficiency', models.FloatField(default=0.0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andon.station')),
            ],
        ),
    ]
