# Generated by Django 5.2.6 on 2025-09-26 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('meter', 'Energy Meter'), ('sensor', 'Sensor'), ('monitor', 'Power Monitor')], max_length=50)),
                ('located_at', models.CharField(max_length=100)),
                ('device_address', models.URLField(help_text='HTTP endpoint of the device', max_length=255)),
                ('latest_value', models.JSONField(blank=True, help_text='Latest data received from device', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('polling_interval', models.IntegerField(default=60, help_text='Polling interval in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device',
                'ordering': ['-created_at'],
                'unique_together': {('device_owner', 'device_address')},
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='devices.device')),
            ],
            options={
                'db_table': 'device_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='device_data_device__ac13fc_idx')],
            },
        ),
    ]
