# Generated by Django 5.2.6 on 2025-09-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_address',
            field=models.CharField(help_text='IP address of the device', max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='polling_interval',
            field=models.IntegerField(default=5, editable=False, help_text='Polling interval in seconds'),
        ),
    ]
