# Generated by Django 5.2.6 on 2025-09-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='address_type',
            field=models.CharField(choices=[('ip', 'IP Address'), ('api', 'API Endpoint')], default='ip', max_length=3),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_address',
            field=models.CharField(help_text='Device IP address or API endpoint URL', max_length=200),
        ),
    ]
