# Generated by Django 5.2.6 on 2025-09-26 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_address_type_alter_device_device_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_power_factor', models.FloatField()),
                ('max_power_factor', models.FloatField()),
                ('min_power_factor_time', models.DateTimeField()),
                ('max_power_factor_time', models.DateTimeField()),
                ('avg_power_factor', models.FloatField()),
                ('total_kwh', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_reports', to='devices.device')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='devices.shift')),
            ],
            options={
                'db_table': 'shift_reports',
                'ordering': ['-date', 'shift__start_time'],
                'unique_together': {('shift', 'device', 'date')},
            },
        ),
    ]
