# Generated by Django 5.2.6 on 2025-10-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_shift_shiftreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='polling_interval',
            field=models.IntegerField(default=0.5, editable=False, help_text='Polling interval in seconds'),
        ),
    ]
