# Generated by Django 5.2.6 on 2025-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_polling_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='polling_interval',
            field=models.FloatField(default=0.5, editable=False, help_text='Polling interval in seconds'),
        ),
    ]
