# Generated by Django 5.2.6 on 2025-10-07 05:48

import devices.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='value',
            field=devices.fields.EncryptedJSONField(blank=True, null=True),
        ),
    ]
