# Generated by Django 5.2.6 on 2025-10-07 10:37

import devices.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0013_reencrypt_device_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_secret",
            field=devices.fields.EncryptedJSONField(
                blank=True,
                help_text="Encrypted API credential shared with the device",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="device_secret_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="SHA-256 hash of the active device credential",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="provisioning_state",
            field=models.CharField(
                choices=[("active", "Active"), ("pending", "Pending Claim")],
                default="active",
                help_text="Tracks whether the device has completed credential provisioning",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DeviceProvisioningToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional context captured during provisioning",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_tokens",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "device_provisioning_tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
