# Generated by Django 5.2.6 on 2025-10-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0014_device_device_secret_deviceprovisioningtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceprovisioningtoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
