# Generated by Django 5.2.6 on 2025-10-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0015_alter_deviceprovisioningtoken_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftreport",
            name="avg_current",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="avg_voltage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="data_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="max_current",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="max_current_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="max_voltage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="max_voltage_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="min_current",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="min_current_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="min_voltage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="min_voltage_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
