# Generated by Django 5.2.6 on 2025-10-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_shiftreport_avg_current_shiftreport_avg_voltage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='duid',
            field=models.UUIDField(editable=False, help_text='Device universal identifier used for cross-system correlation', null=True, blank=True),
        ),
    ]
