# Generated by Django 5.2.6 on 2025-10-13 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_populate_device_duids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='duid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Device universal identifier used for cross-system correlation', unique=True),
        ),
    ]
