# Generated by Django 5.2.6 on 2025-10-13 06:15

import devices.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_alter_device_duid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_address',
            field=devices.fields.EncryptedCharField(help_text='Device IP address or API endpoint URL (encrypted)', max_length=500),
        ),
        migrations.AlterField(
            model_name='device',
            name='duid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Device universal identifier used for cross-system correlation', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='latest_value',
            field=devices.fields.EncryptedJSONField(blank=True, help_text='Latest data received from device (encrypted)', null=True),
        ),
    ]
