# Generated by Django 5.2.6 on 2025-10-27 05:37

import devices.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0020_alter_device_device_address_alter_device_duid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="encryption_key_b64",
            field=devices.fields.EncryptedCharField(
                blank=True,
                help_text="Base64 encoded AES key issued to the device",
                max_length=256,
                null=True,
            ),
        ),
    ]
