# Generated by Django 5.2.6 on 2025-10-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_device_encryption_key_b64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('meter', 'Energy Meter'), ('gas_monitor', 'Gas Monitor'), ('andon', 'Andon Station')], max_length=50),
        ),
    ]
