# Generated by Django 5.2.6 on 2025-10-29 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0022_alter_device_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasMonitorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('fault', 'Fault')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(help_text='Link to the core devices.Device entry.', on_delete=django.db.models.deletion.CASCADE, related_name='gas_monitor', to='devices.device')),
            ],
            options={
                'verbose_name': 'Gas Monitor',
                'verbose_name_plural': 'Gas Monitors',
                'ordering': ['-installation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GasMonitorTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gas_level', models.FloatField()),
                ('unit', models.CharField(default='ppm', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='gas_monitor.gasmonitordevice')),
            ],
            options={
                'verbose_name': 'Gas Monitor Reading',
                'verbose_name_plural': 'Gas Monitor Readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='gasmonitordevice',
            index=models.Index(fields=['status'], name='gas_monitor_status_8ad38e_idx'),
        ),
        migrations.AddIndex(
            model_name='gasmonitordevice',
            index=models.Index(fields=['location'], name='gas_monitor_locatio_3d13bd_idx'),
        ),
        migrations.AddIndex(
            model_name='gasmonitortelemetry',
            index=models.Index(fields=['timestamp'], name='gas_monitor_timesta_9ef8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='gasmonitortelemetry',
            index=models.Index(fields=['device', 'timestamp'], name='gas_monitor_device__1b14dd_idx'),
        ),
    ]
