# Generated by Django 5.2.6 on 2025-09-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_manager_email",
            field=models.EmailField(
                blank=True, help_text="Email to receive daily reports", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shift_manager_email",
            field=models.EmailField(
                blank=True, help_text="Email to receive shift reports", max_length=255
            ),
        ),
    ]
