# Generated by Django 5.2.6 on 2025-10-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_reportrecipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportrecipient",
            name="last_failure_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportrecipient",
            name="last_failure_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reportrecipient",
            name="last_success_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

