# Generated by Django 5.2.6 on 2025-10-09 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device_gateway", "0002_device_source_device"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="device",
            new_name="device_gate_owner_i_a1f14c_idx",
            old_name="device_owner_created_idx",
        ),
        migrations.RenameIndex(
            model_name="deviceprovisioningtoken",
            new_name="device_gate_device__6e907e_idx",
            old_name="token_device_expiry_idx",
        ),
        migrations.RenameIndex(
            model_name="devicetelemetry",
            new_name="device_gate_device__d42cd2_idx",
            old_name="telemetry_device_latest_idx",
        ),
    ]
