# Generated by Django 5.2.6 on 2025-10-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "device_gateway",
            "0003_rename_device_owner_created_idx_device_gate_owner_i_a1f14c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceprovisioningtoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
