# Generated by Django 5.2.6 on 2025-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_gateway", "0004_alter_deviceprovisioningtoken_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="encryption_key_b64",
            field=models.CharField(
                blank=True,
                help_text="Base64 encoded AES key shared with the device.",
                max_length=256,
                null=True,
            ),
        ),
    ]
